accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('contactus/', views.contact_us, name='contactus'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('success/', views.success, name='success')
]

ecommerence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('vendor/', include('vendor.urls')),
    path('retailer/', include('retailer.urls')),

     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retailer/urls.py
from django.urls import path, include
from . import views

urlpatterns =[
    path('', views.mainpage, name='retailer'),
    path('edit_retailer/', views.edit_retailer, name='edit_retailer'),

    path('products/', views.products_view, name='products'),
    path('product/<product_slug>', views.product, name='product'),
    path('discount/', views.discounts, name='retailer_discounts'),

    path('vendors/', views.vendors_view, name='retailer_vendors'),
    path('vendors/<vendor_slug>', views.vendor, name='retailer_vendor'),

    path('cart/', views.carts, name='retailer_carts'),
    path('cart/<vendor_slug>', views.vendor_cart, name='vendor_cart'),
    path('cart/success/', views.order_success, name='order_success'),

    path('order/current', views.current_order_view, name='retailer_current_orders'),
    path('order/final', views.final_order_view, name='retailer_final_orders'),
]

retailer/models.py
from django.db import models
from accounts.models import Account, City, Region


# Create your models here.
class Retailer(models.Model):
    user         = models.OneToOneField(Account, related_name='retailer', on_delete=models.CASCADE, primary_key=True)  # فیلدهای عمومی
    # other fields
    name = models.CharField('نام', max_length=255, blank=True)
    slug = models.SlugField(max_length=55, null=True, unique=True)

    city         = models.ForeignKey(City, null=True, verbose_name='شهر', related_name='retailer', on_delete=models.CASCADE)
    eco_num      = models.CharField(' کد اقتصادی ', max_length=12, blank=False, unique=True)  # شماره اقتصادی
    post_code    = models.CharField(' کد پستی ', default='', max_length=10, blank=False)  # کد پستی
    region       = models.ForeignKey(Region, null=True, verbose_name='منطقه', related_name='retailer', on_delete=models.CASCADE)  # منطقه
    full_add     = models.CharField(' آدرس کامل ', default='', max_length=150, null=True, blank=True)  # آدرس کامل


    manager_name = models.CharField('نام مدیر', default='', blank=True, max_length=30)
    manager_phone = models.CharField(' شماره مدیر', default='', max_length=20, blank=False)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import Account


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError(" رمز عبور یا ایمیل اشتباه است ")


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

	class Meta:
		model = Account
		fields = ('email', 'phone', 'username',  'password1', 'password2')

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError(' این ایمیل قبلا استفاده شده است')

	def clean_phone(self):
		phone = self.cleaned_data['phone']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(phone=phone)
		except Account.DoesNotExist:
			return phone
		raise forms.ValidationError(' این شماره قبلا استفاده شده است')


	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError(' این نام کاربری قبلا استفاده شده است')

retailer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import Account



class AddToCartForm(forms.Form):
	quantity = forms.IntegerField()


class OrderSettelementForm(forms.Form):
	cash_settlement = forms.BooleanField()
	draft_settlement = forms.BooleanField()
	trust_settlement = forms.BooleanField()

retailer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from . import forms
from cart.cart import Cart
from product.models import Category
from vendor.models import VendorProduct, Vendor
from order.models import Order
from order.utilities import retailer_order_record, retailer_orders_record


# Create your views here.


@login_required()
def mainpage(request):
	cart = Cart(request)
	retailer = request.user.retailer

	return render(request, 'retailer\mainpage.html', {'retailer': retailer,
													  'cart': cart})


@login_required()
def products_view(request):
	cart = Cart(request)
	retailer = request.user.retailer

	# categories that vendors add product from it
	categories = (category for category in Category.objects.all() if category.vendor_products)

	# محصولات توزیع کننده های شهر مربوط به فروشگاه
	city = retailer.city
	vendors = city.vendor.all()
	products = set()
	for vendor in vendors:
		products.update(vendor.get_exist_product())

#	products = random.sample(products, 50)
	return render(request, 'retailer\product\products.html', {'retailer': retailer,
															  'products': products,
															  'categories': categories,
															  'cart': cart})

@login_required()
def product(request, product_slug):
	retailer = request.user.retailer
	product = get_object_or_404(VendorProduct, slug=product_slug)
	vendor_slug = product.vendor.slug

	cart = Cart(request)

	if request.POST:
		form = forms.AddToCartForm(request.POST)
		if form.is_valid():
			quantity = form.cleaned_data['quantity']
			cart.add(vendor_slug=vendor_slug, product_slug=product.slug, quantity=quantity, update_quantity=False)

			return redirect('products')
	else:
		form = forms.AddToCartForm()


	return render(request, 'retailer/product/product.html', {'cart': cart,
															 'retailer': retailer,
															 'product': product,
															 'form': form})


@login_required()
def discounts(request):
	cart = Cart(request)
	retailer = request.user.retailer

	city = retailer.city
	vendors = city.vendor.all()
	products = set()
	for vendor in vendors:
		products.update(vendor.get_discounted_products())

	categories = Category.objects.all()

	return render(request, 'retailer\product\discounts.html', {'retailer': retailer,
															 'products': products,
															 'categories': categories,
															   'cart': cart})


@login_required()
def vendors_view(request):
	cart = Cart(request)
	retailer = request.user.retailer
	city = retailer.city
	vendors = city.vendor.all()

	return render(request, 'retailer\\vendor\\vendors_view.html', {'retailer': retailer,
																   'vendors': vendors,
																   'cart': cart})




@login_required()
def vendor(request, vendor_slug):
	cart = Cart(request)
	retailer = request.user.retailer
	vendor = get_object_or_404(Vendor, slug=vendor_slug)

	return render(request, 'retailer\\vendor\\vendor.html', {'cart': cart,
															 'retailer': retailer,
															 'settlement': vendor.settlement,
															 'vendor': vendor})




@login_required()
def carts(request):
	cart = Cart(request)
	retailer = request.user.retailer

	remove_vendor = request.GET.get('remove_vendor', '')
	if remove_vendor:
		cart.remove_vendor(remove_vendor)
		return redirect('retailer_carts')

	remove_product = request.GET.get('remove_product', '')  # get vendor product slug
	vendor_product = request.GET.get('vendor_product', '')
	if remove_product:
		cart.remove_product(vendor_product, remove_product)
		return redirect('retailer_carts')


	change_quantity = request.GET.get('change_quantity', '')
	vendor = request.GET.get('vendor', '')
	quantity = request.GET.get('quantity', 0)
	if change_quantity:
		cart.add(vendor, change_quantity, quantity, update_quantity=True)
		return redirect('retailer_carts')


	save_orders = request.GET.get('save_orders', '')
	if save_orders:
		orders = retailer_orders_record(request)


		if orders:
			cart.clear()
			#notify_vendor(order)
			#notify_retailer(order)
			return redirect('order_success')

	return render(request, 'retailer\cart\cart.html', {'cart': cart,
													   'retailer': retailer})


@login_required()
def vendor_cart(request, vendor_slug):
	retailer = request.user.retailer
	cart = Cart(request)
	for vendor_cart in cart:
		if vendor_cart['vendor'].slug == vendor_slug:

			removed_vendor = request.GET.get('remove_vendor', '')
			if removed_vendor:
				cart.remove_vendor(removed_vendor)
				return redirect('retailer')

			remove_product = request.GET.get('remove_product', '')  # get vendor product slug
			vendor_product = request.GET.get('vendor_product', '')
			if remove_product:
				cart.remove_product(vendor_product, remove_product)
				return redirect('cart')


			change_quantity = request.GET.get('change_quantity', '')
			vendor = request.GET.get('vendor', '')
			quantity = request.GET.get('quantity', 0)
			if change_quantity:
				cart.add(vendor, change_quantity, quantity, update_quantity=True)
				return redirect('cart')



			return render(request, 'retailer\cart\\vendor_cart.html', {'retailer': retailer,
																	   'vendor_settlement': vendor_cart['vendor'].settlement,
																	   'cart': cart,
																	   'vendor_cart': vendor_cart})


@login_required()
def order_success(request):
	retailer = request.user.retailer
	cart = Cart(request)

	return render(request, 'retailer\cart\success.html', {'cart': cart,
														  'retailer': retailer})


@login_required()
def current_order_view(request):
	retailer = request.user.retailer
	cart = Cart(request)
	orders = retailer.orders.all()
	orders = orders.filter(buyer_confirmation=False)

	order_confirmation = request.GET.get('order_confirmation', '')
	if order_confirmation:
		order = Order.objects.get(id=order_confirmation)
		order.buyer_confirmation = True
		order.save()
		return redirect('retailer_current_orders')

	return render(request, 'retailer\order\current_orders.html', {'retailer': retailer,
																  'cart': cart,
																  'orders': orders})


@login_required()
def final_order_view(request):
	retailer = request.user.retailer
	cart = Cart(request)

	orders = retailer.orders.all()
	orders = orders.filter(buyer_confirmation=True)

	return render(request, 'retailer\order\\final_orders.html', {'retailer': retailer,
																 'cart': cart,
																 'orders': orders})


@login_required
def edit_retailer(request):
	retailer = request.user.retailer
	cart = Cart(request)

	if request.method == 'POST':
		name = request.POST.get('name', '')
		email = request.POST.get('email', '')
		username = request.POST.get('username', '')
		phone = request.POST.get('phone', '')
		manager_name = request.POST.get('manager_name', '')
		manager_phone = request.POST.get('manager_phone', '')
		if name:
			retailer.user.email = email
			retailer.user.username = username
			retailer.user.save()

			retailer.name = name
			retailer.phone = phone
			retailer.manager_name = manager_name
			retailer.manager_phone = manager_phone
			retailer.save()
			return redirect('retailer_mainpage')

	return render(request, 'retailer/edit_retailer.html', {'retailer': retailer,
														   'cart': cart})


templates/retailer/base.html
<!DOCTYPE html>


{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} سامانه توزیع کالا {% endblock title %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    <div class="container">
        <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'retailer' %}">
                <img src="media/defaults/logo/brand1.jpg" width="112" >
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                <a class="navbar-item" href="{% url 'retailer' %}">
                    صفحه اصلی
                </a>


                </div> <!-- navbar start -->

                <div class="navbar-end">

                    <div class="navbar-item has-dropdown is-hoverable">
                        <span class="navbar-link"><a href="{% url 'retailer_carts'%}">
                            سبدخرید {% if cart %} ({{ cart|length }}) {% endif %}
                        </a></span>
                    </div>


                    <div class="navbar-item">
                        <a class="button is-dark" href="{% url 'retailer_vendors' %}">
                            نمایندگان
                        </a>
                    </div>

                    <div  class="navbar-item">
                        <a class="button is-dark" href="{% url 'products' %}">
                            کالا
                        </a>
                    </div>
                    <div class="navbar-item">
                        <a class="button is-dark" href="{% url 'retailer_discounts' %}">
                            تخفیفات
                        </a>
                    </div>

                    <div class="navbar-item">
                        <a class="navbar-link" href="{% url 'retailer_current_orders' %}"> سفارشات </a>
                    </div>

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link is-capitalized">
                        {{ retailer.user.username }}
                        </a>

                        <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'retailer' %}">
                            پروفایل
                        </a>
                        <a class="navbar-item" href="{% url 'edit_retailer' %}">
                            تغییر اطلاعات کاربری
                        </a>
                        <a class="navbar-item" href="{% url 'password_change' %}">
                            تغیر رمز عبور
                        </a>
                        <a class="navbar-item" href="{% url 'contactus' %}">
                                <strong> ارتباط با ما</strong>
                        </a>
                        <a class="navbar-item" href="{% url 'logout' %}">
                            خروج
                        </a>

                        </div>
                    </div>
                </div> <!--navbarend -->
                </div> <! --nav basic exam -->
            </nav>
    </div>

    <section class="section">
        <div class="container">

            {% block content %}{% endblock content %}

        </div>
    </section>


    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}

</body>
</html>

templates/retailer/edit_retailer.html
{% extends 'retailer/base.html' %}

{% block title %}اطلاعات کاربری{% endblock %}

{% block content %}
    <h1 class="title">تغییر اطلاعات کاربری</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="field">
            <label>نام کاربری</label>
            <div class="control">
                <input type="text" name="username" value="{{ retailer.user.username }}" class="input">
            </div>
        </div>

        <div class="field">
            <label>نام</label>
            <div class="control">
                <input type="text" name="name" id="id_name" value="{{ retailer.name }}" class="input">
            </div>
        </div>

        <div class="field">
            <label>ایمیل</label>

            <div class="control">
                <input type="email" name="email" id="id_email" value="{{ retailer.user.email }}" class="input">
            </div>
        </div>

        <div class="field">
            <label>شماره تماس اصلی</label>

            <div class="control">
                <input type="number" name="phone" value="{{ retailer.phone }}" class="input">
            </div>
        </div>

        <div class="field">
            <label>نام مسئول خرید</label>

            <div class="control">
                <input type="text" name="manager_name" value="{{ retailer.manager_name }}" class="input">
            </div>
        </div>

        <div class="field">
            <label>شماره تماس مسئول خرید</label>

            <div class="control">
                <input type="number" name="manager_phone" value="{{ retailer.manager_phone}}" class="input">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button type='submit' class="button is-dark is-uppercase">ذخیره اطلاعات</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/retailer/mainpage.html
{% extends 'retailer/base.html' %}

{% block title %}فروشگاه{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3"> {{ retailer.name}} </h2>
        </div>
        <div>

        </div>

    </div>
{% endblock content %}